HAI
    I HAS A VAR1
    VAR1 R SUM OF 123 AN 321
    VAR1 R DIFF OF 123 AN 321
    VAR1 R DIFF OF 123 AN 321
    VAR1 R PRODUKT OF 123 AN 321
    VAR1 R QUOSHUNT OF 123 AN 321
    VAR1 R BIGGR OF 123 AN 321
    VAR1 R SMALLR OF 123 AN 321
    VAR1 R MOD OF 123 AN 321
    VISIBLE BOTH SAEM "WIN" AN "FALSE"
    VISIBLE DIFFRINT "ONE" AN "TWO"
    VISIBLE BOTH OF BOTH SAEM "TRUE" AN "TRUE" AN DIFFRINT "THIS" AN "THAT"
    VISIBLE ONE OF BOTH SAEM "TRUE" AN "TRUE" AN DIFFRINT "THIS" AN "THAT"
    VISIBLE EITHER OF BOTH SAEM "TRUE" AN "TRUE" AN DIFFRINT "THIS" AN "THAT"
KTHXBYE
