HAI
    I HAS A TST
    I HAS A TST2
    IM IN YR LOOP1 UPPIN YR TST TIL SUM OF TST AN 128
        I HAS A TST2
        VISIBLE TST
    IM OUTTA YR LOOP1
    IM IN YR LOOP2 NERFIN YR TST WILE SUM OF TST AN 128
        VISIBLE TST2
    IM OUTTA YR LOOP2
    IM IN YR LOOP3 NERFIN YR TST TIL SUM OF TST AN 128
        VISIBLE TST
        IM IN YR LOOP4 NERFIN YR TST WILE SUM OF TST AN 128
            VISIBLE TST
        IM OUTTA YR LOOP3
    IM OUTTA YR LOOP4
KTHXBYE
